import { OriginSummary } from "./OriginSheets";
import type { CharacterBuild, DerivedCharacter, SkillId } from "../../rules/types";
import type { PlayState } from "../../rules/engine/playState";
import { derivePrimalCompanion } from "../../rules/engine/primalCompanion";
import { PRIMAL_FORMS } from "../../data/ranger";
import { spell } from "../../data/spells";
import { ABILITIES, SKILLS } from "../../data/core";
import { features, itemNames, damageNames, masteryDescriptions } from "../../data/characterDetails";
import { WEAPONS } from "../../data/weapons";
import { abilityNames, skillNames, masteryName, zhCN } from "../../translations/zh-CN";
import { signed, damageFormula } from "../../rules/engine/format";
import { Header, Stats, Resources } from "./CharacterSheets";

export function RangerSheets({ build, c, play, mode }: { build: CharacterBuild; c: DerivedCharacter; play: PlayState; mode: "quick" | "full" }) {
  const full = mode === "full"; const total = full ? 5 : 3; const b = play.primal!; const beast = derivePrimalCompanion(c, b.choice); const casting = c.spellcasting!;
  const header = (title: string, page: number) => <Header build={build} title={title} page={`${page} / ${total}`} />;
  // 伙伴使用当前冒险状态，初始外形编辑不会修改这张数据卡。
  return <><article className="sheet-page" data-sheet-page>{header(full ? "完整人物卡 · 游侠" : "游侠 · 战斗速查", 1)}<Stats c={c} play={play} /><p className="casting-strip">感知施法 · 攻击 {signed(casting.attack)} · DC {casting.dc} · 专注：{spell(play.rangerConcentration ?? "")?.name ?? "无"}</p><div className="sheet-abilities">{ABILITIES.map((id) => <div key={id}><small>{abilityNames[id]}</small><b>{c.abilities[id].score}</b><span>{signed(c.abilities[id].modifier)}</span></div>)}</div>
    {full && <div className="sheet-columns"><section><h3>豁免 · ● 熟练</h3><div className="sheet-rolls">{ABILITIES.map((id) => <div key={id}><span>{c.savingThrows[id].proficiency === "proficient" ? "●" : "○"} {abilityNames[id]}</span><b>{signed(c.savingThrows[id].modifier)}</b></div>)}</div><p>轻甲、中甲、盾牌训练；简易与军用武器熟练。黑暗视觉 120 尺、毒素伤害抗性；避免或结束中毒的豁免具有优势。</p><p>被动察觉 {c.passivePerception} · 中型类人生物。</p></section><section><h3>技能 · ● 熟练 / ◆ 专精</h3><div className="sheet-rolls">{(Object.keys(SKILLS) as SkillId[]).map((id) => <div key={id}><span>{c.skills[id].proficiency === "expertise" ? "◆" : c.skills[id].proficiency === "proficient" ? "●" : "○"} {skillNames[id]}</span><b>{signed(c.skills[id].modifier)}</b></div>)}</div></section></div>}
    <section><h3>武器攻击 · 攻击动作通常一次攻击</h3><table className="sheet-attacks"><thead><tr><th>武器</th><th>命中</th><th>伤害</th><th>精通</th></tr></thead><tbody>{c.attacks.map((a) => <tr key={a.weaponId}><td><b>{itemNames[a.weaponId]}</b><small>{WEAPONS[a.weaponId].properties}{a.range ? ` · ${a.range.join(" / ")} 尺` : " · 5 尺"}</small>{a.disadvantage && <small>{a.disadvantage}</small>}</td><td>{signed(a.attackBonus)}</td><td>{damageFormula(a.damageDice, a.damageModifier)} {damageNames[a.damageType]}</td><td>{a.mastery?.unlocked ? masteryName(a.mastery.id) : "未解锁"}</td></tr>)}</tbody></table>{!full && <p className="sheet-note">轻型武器额外攻击需使用另一把轻型武器，不加正属性伤害调整值；如解锁迅击，可纳入攻击动作，每回合仅一次。此方案没有双武器战斗风格。超过正常射程有劣势；不可超过最大射程。远程重型武器要求敏捷至少 13。</p>}</section>
    {!full && <><Resources c={c} play={play} /><OriginSummary c={c} /></>}{!full && <p className="sheet-note">体质豁免 {signed(c.savingThrows.constitution.modifier)}；维持专注 DC=max(10,伤害一半向下取整)，上限 30，临时 HP 承伤也需检定。失能或 0 HP 结束专注；三级没有专注保护，也没有额外攻击。</p>}
    {!full && <footer className="sheet-footer">猎人印记：仅游侠本人攻击命中加 1d6 力场。指挥伙伴与施展／转移印记争用附赠动作。</footer>}</article>
    {full && <article className="sheet-page" data-sheet-page>{header("完整人物卡 · 能力与资源", 2)}<Resources c={c} play={play} /><div className="sheet-features">{c.features.map((id) => <div key={id}><b>{features[id]?.name}</b><small>{features[id]?.timing}</small><p>{features[id]?.text}</p></div>)}</div><section><h3>精通速查</h3>{build.choices.weaponMasteries.map((id) => <p key={id}><b>{itemNames[id]} · {masteryName(WEAPONS[id].mastery)}</b>：{masteryDescriptions[WEAPONS[id].mastery]}</p>)}</section><p className="sheet-note">轻型武器额外攻击需使用另一把轻型武器，不加正属性伤害调整值；如解锁迅击，可纳入攻击动作，每回合仅一次。此方案没有双武器战斗风格。超过正常射程有劣势；不可超过最大射程。远程重型武器要求敏捷至少 13。</p><p className="sheet-note">体质豁免 {signed(c.savingThrows.constitution.modifier)}；维持专注 DC=max(10,伤害一半向下取整)，上限 30，临时 HP 承伤也需检定。失能或 0 HP 结束专注；三级没有专注保护，也没有额外攻击。</p></article>}
    {full && <article className="sheet-page" data-sheet-page>{header("完整人物卡 · 装备与身份", 3)}<div className="sheet-columns"><section><h3>起始装备</h3><div className="sheet-rolls">{c.equipment.map((e) => <div key={e.id}><span>{itemNames[e.id]}</span><b>× {e.quantity}</b></div>)}</div><p>镶钉皮甲已着装；起始装备没有盾牌。箭矢、消耗品和装备变化请另行记录。</p></section><section><h3>语言与工具</h3><p>{c.languages.map((id) => zhCN.language[id as keyof typeof zhCN.language]).join("、")}</p><p>工具熟练：{c.tools.map((id) => itemNames[id] ?? id).join("、")}。</p><h3>施法成分</h3><p>槲寄生枝条作为德鲁伊法器，替代无标价且不消耗的材料。姿势需自由手；持法器之手可完成同一法术的材料与姿势成分。双手武器攻击与施法时注意腾出手。</p><h3>探索套组</h3><p>背包、铺盖、2 瓶油、10 日口粮、绳索、火绒盒、10 支火把、水袋。</p></section></div><section className="sheet-story"><h3>身份</h3><p>{build.identity.gender || "性别未填写"} · {build.identity.age ?? "—"} 岁 · {build.identity.personalityTraits?.join("、") || "性格未填写"}</p><h4>外貌</h4><p>{build.identity.appearance || "—"}</p><h4>故事</h4><p>{build.identity.description || "—"}</p></section></article>}
    <article className="sheet-page" data-sheet-page>{header("原初行侣 · 伙伴速查", full ? 4 : 2)}<h3>{beast.name} · {b.choice.appearance}</h3><p>{beast.size}野兽 · 中立 · {b.status === "alive" ? b.hp > 0 ? "存活" : "0 HP，待处理昏迷或死亡" : b.status === "dead" ? "死亡" : b.status === "reviving" ? "复活等待中" : "已消失"}</p><div className="sheet-stats"><div><small>伙伴 HP</small><strong>{b.hp}<sub> / {beast.hp}</sub></strong><small>临时 HP {b.temporaryHp}</small></div><div><small>AC</small><strong>{beast.armorClass}</strong><small>13 + 游侠感知</small></div><div><small>野兽打击命中</small><strong>{signed(beast.attack)}</strong><small>游侠法术攻击</small></div><div><small>生命骰</small><strong>{b.hitDice}<sub> / 3d{beast.hitDie}</sub></strong><small>独立于游侠</small></div></div><p>{beast.speed} · 黑暗视觉 {beast.darkvision} 尺 · 被动察觉 {beast.passivePerception}（含原初联结） · 理解你说的语言。</p><div className="sheet-abilities">{ABILITIES.map((id) => <div key={id}><small>{abilityNames[id]}</small><b>{beast.abilities[id]}</b><span>检定／豁免 {signed(beast.rolls[id])}</span></div>)}</div><p>原初联结：全部属性检定和豁免加你的熟练加值，以上已计入；不重复加熟练。先攻 {signed(beast.rolls.dexterity)}，但战斗中跟随你的回合。</p><section><h3>野兽打击</h3><p>近战攻击 {signed(beast.attack)} · 触及 5 尺 · {beast.damage} {damageNames[b.choice.damage]}。</p><p>{beast.effect}{b.choice.form === "sea" ? ` 逃脱 DC ${beast.dc}。` : ""}</p><p>三级伙伴不获得猎人印记加伤，不具有七级附赠动作训练或十一级双重打击。</p></section><section><h3>如何指挥</h3><p>伙伴在你的回合行动，可自主移动、使用反应；未被指挥时只回避。花你的附赠动作，指挥其执行野兽打击或其他动作；也可牺牲攻击动作中的一次攻击，仅指挥野兽打击。你失能时它自主行动；你死亡时它消失。</p></section><section><h3>恢复与替换</h3><p>伙伴有独立 HP、临时 HP 与生命骰；短休可花自身生命骰治疗。0 HP 不自动等于死亡，由主持人裁定。死亡不超过 1 小时，可用魔法动作消耗一个法术位，1 分钟后复活并回满 HP；宿敌免费施法次数不能替代法术位。长休后可召唤新的伙伴，新伙伴出现时旧伙伴消失。</p></section><p className="sheet-note">三种数据卡：{PRIMAL_FORMS.map((f) => `${f.name} HP ${f.hp}，${f.speed}`).join("；")}。外观不授予额外普通野兽能力。伤害类型在召唤时选择。</p></article>
    <article className="sheet-page" data-sheet-page>{header("游侠 · 已准备法术", total)}<p className="casting-strip">感知 · 攻击 {signed(casting.attack)} · DC {casting.dc} · 一环位剩余 {play.remaining["spell-slot-1"]}/3 · 宿敌剩余 {play.remaining["favored-enemy"]}/2</p><div className="spell-card-grid">{casting.prepared.map((id) => { const s = spell(id)!; return <section className="spell-card" key={id}><h3>{s.name} <small>一环 · {s.school}</small></h3><div className="spell-source">{id === "hunters-mark" ? "宿敌 · 始终准备 · 可免费或用法术位" : "职业准备"}{s.ritual ? " · 可仪式" : ""}</div><p><b>{s.time}</b> · {s.range}<br />{s.components}<br />{s.concentration ? "专注 · " : ""}{s.duration}</p><p>{s.text}</p>{c.features.includes("healer") && ["cure-wounds", "healing-word"].includes(id) && <p>医疗师：治疗骰掷出 1 可重掷，必须使用新结果。</p>}</section>; })}</div><footer className="sheet-footer">一回合只能消耗一个法术位施法。仪式额外花 10 分钟、不扣位，但需要专注。每次长休仅替换一道准备法术；本页为当前构筑记录。</footer></article>
  </>;
}
