import { useState } from "react";
import { PRIMAL_FORMS, primalForm, type PrimalChoice } from "../../data/ranger";
import { damageNames } from "../../data/characterDetails";
import { spell } from "../../data/spells";
import { derivePrimalCompanion } from "../../rules/engine/primalCompanion";
import type { PlayAction, PlayState } from "../../rules/engine/playState";
import type { DerivedCharacter } from "../../rules/types";
import { signed } from "../../rules/engine/format";
import { useBuilder } from "../../store/builder";

export function RangerPlayPanel({ c, play }: { c: DerivedCharacter; play: PlayState }) {
  const { dispatch } = useBuilder(); const b = play.primal!; const beast = derivePrimalCompanion(c, b.choice);
  const [selected, setSelected] = useState("hunters-mark"); const [damage, setDamage] = useState(0); const [playerDamage, setPlayerDamage] = useState(0);
  const [withinHour, setWithinHour] = useState(false); const [replacement, setReplacement] = useState<PrimalChoice>(b.choice);
  const update = (action: PlayAction) => dispatch({ type: "play", action }); const canAct = play.hp > 0 && !play.incapacitated;
  const spellId = c.spellcasting!.prepared.includes(selected) ? selected : "hunters-mark";
  // 待选替换数据与当前伙伴分离；确认召唤前不修改 HP、形态或伤害类型。
  return <section className="play-panel ranger-panel no-print" aria-label="游侠与伙伴记录"><h2>游侠与原初行侣</h2><p>指挥伙伴、施展猎人印记或转移印记均会用到附赠动作；一回合通常只有一个附赠动作。</p>
    <div className="form-grid"><label>游侠施法<select value={spellId} onChange={(e) => setSelected(e.target.value)}>{c.spellcasting!.prepared.map((id) => <option key={id} value={id}>{spell(id)?.name}</option>)}</select></label><button className="button primary" disabled={!canAct || play.remaining["spell-slot-1"] === 0} onClick={() => update({ type: "ranger-cast", spellId })}>施展并消耗一环法术位</button></div>
    <div className="rest-actions"><button className="button secondary" disabled={!canAct || play.remaining["favored-enemy"] === 0} onClick={() => update({ type: "ranger-cast", spellId: "hunters-mark", free: true })}>宿敌 · 免费施展猎人印记</button>{play.rangerConcentration && <button className="button secondary" onClick={() => update({ type: "end-ranger-concentration" })}>结束专注</button>}</div><p>当前专注：{spell(play.rangerConcentration ?? "")?.name ?? "无"}。转移仍生效的印记不再扣次数；玩家确认目标与触发条件。新专注替换旧专注。</p><p className="hint">已准备的仪式可额外花 10 分钟、不扣位施展，请勿点扣位按钮。仪式施法需要专注；原有专注应先结束。治疗量、持续时间和豁免由玩家记录。</p>
    <div className="form-grid"><label>游侠承受伤害<input type="number" min={0} value={playerDamage} onChange={(e) => setPlayerDamage(Number(e.target.value))} /></label><button className="button secondary" onClick={() => { update({ type: "damage", amount: playerDamage }); setPlayerDamage(0); }}>记录游侠伤害</button></div><p className="hint">受伤后仍须作专注豁免，失败点「结束专注」；临时 HP 承伤也要检定。</p><label className="inline-check"><input type="checkbox" checked={!!play.incapacitated} onChange={(e) => update({ type: "incapacitated", value: e.target.checked })} />游侠失能（结束专注，伙伴可自主行动）</label>
    <h3>{beast.name} · {b.choice.appearance}</h3><p>AC {beast.armorClass} · HP {b.hp}/{beast.hp} · 临时 HP {b.temporaryHp} · {beast.speed}</p><p>野兽打击：命中 {signed(beast.attack)}，{beast.damage} {damageNames[b.choice.damage]}，近战 5 尺。{beast.effect}</p><p className="muted-panel">{b.status === "absent" ? "伙伴已消失；需完成长休后召唤新伙伴。" : b.status === "dead" ? "伙伴死亡，不能行动。" : b.status === "reviving" ? "正在等待复活，一分钟过去前不能行动。" : b.hp === 0 ? "伙伴 0 HP，不能行动；由主持人处理昏迷、稳定或死亡。" : !canAct ? "游侠失能，伙伴可以自主行动，无须指挥。" : "伙伴在你的回合行动，自主移动与反应；默认回避。附赠动作可指挥其他动作，或牺牲攻击动作中的一次攻击，令伙伴野兽打击。三级没有额外攻击。"}</p>
    <div className="tracker-grid"><label>伙伴当前 HP<input type="number" min={0} max={beast.hp} disabled={b.status !== "alive"} value={b.hp} onChange={(e) => update({ type: "primal-hp", value: Number(e.target.value) })} /></label><label>伙伴临时 HP<input type="number" min={0} max={999} disabled={b.status !== "alive"} value={b.temporaryHp} onChange={(e) => update({ type: "primal-temp", value: Number(e.target.value) })} /></label><label>伙伴剩余生命骰 / 3d{beast.hitDie}<input type="number" min={0} max={3} value={b.hitDice} onChange={(e) => update({ type: "primal-hit-dice", value: Number(e.target.value) })} /></label></div><p className="hint">短休不自动治疗伙伴；花费其生命骰，按掷骰结果记录 HP 与剩余骰数。伙伴体质调整值 {signed(beast.modifiers.constitution)}。</p>
    <div className="form-grid"><label>伙伴承受伤害<input type="number" min={0} value={damage} onChange={(e) => setDamage(Number(e.target.value))} /></label><button className="button secondary" disabled={b.status !== "alive" || damage <= 0} onClick={() => { update({ type: "primal-damage", amount: damage }); setDamage(0); }}>记录伙伴伤害</button></div>
    <div className="rest-actions"><button className="button secondary" disabled={b.status !== "alive"} onClick={() => { update({ type: "primal-dead" }); setWithinHour(false); }}>确认伙伴已经死亡</button>{b.status === "reviving" && <button className="button primary" onClick={() => update({ type: "primal-revive-complete" })}>一分钟已过 · 伙伴复活</button>}</div>
    {b.status === "dead" && <div><label className="inline-check"><input type="checkbox" checked={withinHour} onChange={(e) => setWithinHour(e.target.checked)} />确认伙伴死亡不超过一小时</label><button className="button secondary" disabled={!withinHour || !canAct || play.remaining["spell-slot-1"] === 0} onClick={() => update({ type: "primal-revive", withinHour })}>魔法动作 · 扣一环位开始复活</button><p className="hint">复活需一分钟，恢复伙伴全部 HP；不补回其生命骰。</p></div>}
    <details className="choice-section"><summary>长休后召唤或替换伙伴</summary><p>完成长休后立即可替换一次；开始其他冒险记录操作后资格结束。新伙伴出现时旧伙伴消失。短休、编辑外形或重载不能获得免费治疗。</p><div className="form-grid"><label>新伙伴类型<select value={replacement.form} onChange={(e) => { const f = primalForm(e.target.value)!; setReplacement({ ...replacement, form: f.id, damage: f.damageTypes[0] }); }}>{PRIMAL_FORMS.map((f) => <option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>新伙伴伤害类型<select value={replacement.damage} onChange={(e) => setReplacement({ ...replacement, damage: e.target.value as PrimalChoice["damage"] })}>{primalForm(replacement.form)!.damageTypes.map((id) => <option key={id} value={id}>{damageNames[id]}</option>)}</select></label><label>新伙伴外形<input maxLength={40} value={replacement.appearance} onChange={(e) => setReplacement({ ...replacement, appearance: e.target.value })} /></label></div><button className="button primary" disabled={!b.canReplace || !canAct || !replacement.appearance.trim()} onClick={() => update({ type: "primal-replace", choice: replacement })}>召唤新伙伴</button>{!b.canReplace && <p>先在冒险记录中确认已完成长休。</p>}</details>
    <details className="choice-section"><summary>游侠死亡</summary><p>仅失能或 0 HP 不会使伙伴消失；确认为死亡后再使用此操作。</p><button className="button secondary" onClick={() => update({ type: "ranger-dead" })}>确认游侠死亡 · 伙伴消失</button></details>
  </section>;
}
