import { defaultBuild } from "../src/rules/defaultBuild";
import { deriveCharacter } from "../src/rules/engine/deriveCharacter";
import { deriveWildShape } from "../src/rules/engine/wildShape";
import { normalizePlayState, updatePlayState } from "../src/rules/engine/playState";
import { validateBuild } from "../src/rules/validator/validateBuild";
import { parseDraft, switchClass, type BuilderState } from "../src/store/draft";
import { beast, legalMoonForm } from "../src/data/beasts";

// 覆盖 2024 变形的关键边界：HP 保留、熟练取高、非叠加临时 HP 与原子消耗。
export function druidChecks(assert: (ok: boolean, message: string) => void) {
  const build = defaultBuild("druid");
  build.identity = { name: "苔拉·月痕", alignment: "NG" };
  const c = deriveCharacter(build);
  assert(validateBuild(build).canGenerate, "default moon druid must be legal");
  assert(c.maxHp === 27 && c.hitDie === 8 && c.armorClass === 15, "druid fixed HP, dwarf HP and leather/shield AC");
  assert(c.spellcasting?.attack === 5 && c.spellcasting.dc === 13, "druid uses wisdom");
  assert(c.spellcasting!.prepared.length === 9 && c.spellcasting!.cantrips.length === 4, "automatic spells do not consume selection slots");
  assert(c.skills.nature.modifier === 6 && c.skills.arcana.modifier === 4, "magician adds wisdom to INT nature and arcana");
  assert(c.savingThrows.wisdom.modifier === 5 && c.savingThrows.intelligence.modifier === 3, "druid save proficiency");
  assert(c.languages.includes("druidic") && c.equipment.find((e) => e.id === "gp")?.quantity === 25, "druid language and combined equipment");
  assert(!c.resources.some((r) => ["arcane-recovery", "magic-initiate"].includes(r.id)), "wizard resources must not leak");
  const bear = deriveWildShape(c, "brown-bear");
  assert(bear.maxHp === 27 && bear.hitDie === 8 && bear.abilities.constitution.score === 15, "beast constitution never recalculates retained HP");
  assert(bear.abilities.strength.score === 17 && bear.abilities.wisdom.score === 17, "physical attributes replaced; mental retained");
  assert(bear.armorClass === 16 && bear.speed === 40 && bear.initiative.modifier === 1, "moon armor and beast movement");
  assert(bear.senses.darkvision === 60 && !bear.resistances.includes("poison") && !bear.features.includes("stonecunning"), "species senses and resistance replaced");
  assert(bear.skills.nature.modifier === 6 && bear.skills.perception.modifier === 5, "class feature and proficiency survive form");
  const cat = deriveWildShape(c, "cat");
  assert(cat.savingThrows.dexterity.modifier === 4 && cat.savingThrows.dexterity.proficiency === "proficient", "gain cat save proficiency");
  assert(cat.savingThrows.constitution.modifier === 0 && cat.maxHp === 27, "cat CON save differs while HP stays");
  const forms = structuredClone(build); forms.choices.druid!.knownForms = ["panther", "wolf", "cat", "badger"];
  const panther = deriveWildShape(deriveCharacter(forms), "panther");
  assert(panther.skills.stealth.modifier === 7, "use higher printed beast modifier instead of double-counting proficiency");
  assert(deriveWildShape(c, "panther") === c && deriveWildShape(c, "__proto__") === c, "cannot derive unknown or unselected forms");
  const badger = deriveWildShape(c, "badger");
  assert(badger.maxHp === 27 && badger.abilities.constitution.score === 16 && badger.senses.darkvision === 30 && badger.resistances.includes("poison"), "badger retains HP and has its own defenses");
  assert(beast("brown-bear")!.attacks[1].damage === "1d4+3 挥砍" && beast("cat")!.attacks[0].damage === "1 挥砍（固定）", "MM 2025 attack data, not 2014 variants");
  assert(!legalMoonForm("eagle") && !legalMoonForm("constructor"), "unsupported forms rejected");
  let play = normalizePlayState(undefined, c);
  play = updatePlayState(play, { type: "hp", value: 12 }, c);
  const first = updatePlayState(play, { type: "transform", formId: "badger" }, c);
  assert(first.hp === 12 && first.temporaryHp === 9 && first.remaining["wild-shape"] === 1, "transform consumes once without healing HP");
  assert(play.remaining["wild-shape"] === 2 && !play.formId, "transformation must not mutate input");
  const second = updatePlayState(first, { type: "transform", formId: "brown-bear" }, c);
  assert(second.temporaryHp === 9 && second.remaining["wild-shape"] === 0, "temporary HP do not stack between forms");
  assert(updatePlayState(second, { type: "transform", formId: "cat" }, c).formId === "brown-bear", "exhausted use cannot change form");
  assert(updatePlayState(play, { type: "transform", formId: "panther" }, c).remaining["wild-shape"] === 2, "invalid form cannot consume resource");
  const higher = updatePlayState({ ...play, temporaryHp: 20 }, { type: "transform", formId: "cat" }, c);
  assert(higher.temporaryHp === 20, "higher existing temporary HP preserved");
  const damage = updatePlayState(first, { type: "damage", amount: 11 }, c);
  assert(damage.hp === 10 && damage.temporaryHp === 0 && damage.formId === "badger", "temp HP depleted does not revert form");
  const zero = updatePlayState(damage, { type: "damage", amount: 10 }, c);
  assert(zero.hp === 0 && !zero.formId, "zero HP ends form");
  assert(updatePlayState(zero, { type: "rest", kind: "long" }, c).hp === 0, "long rest requires at least one HP at start");
  assert(!updatePlayState(zero, { type: "transform", formId: "cat" }, c).formId, "zero HP cannot transform");
  const reverted = updatePlayState(first, { type: "revert" }, c);
  assert(!reverted.formId && reverted.hp === 12 && reverted.temporaryHp === 9 && reverted.remaining["wild-shape"] === 1, "revert preserves resource expenditure and HP");
  const incap = updatePlayState(first, { type: "incapacitated", value: true }, c);
  assert(!incap.formId && incap.incapacitated === true, "incapacitated ends form");
  assert(!updatePlayState(incap, { type: "transform", formId: "cat" }, c).formId, "incapacitated blocks transformation");
  const short = updatePlayState({ ...second, remaining: { ...second.remaining, "spell-slot-1": 1 } }, { type: "rest", kind: "short", recover: "two-first" }, c);
  assert(short.remaining["wild-shape"] === 1 && short.remaining["spell-slot-1"] === 1 && short.hp === 12 && !short.formId, "short rest restores one shape, no spell slots or HP");
  const companion = updatePlayState(play, { type: "companion", resource: "spell-slot-1" }, c);
  assert(companion.companion === true && companion.remaining["spell-slot-1"] === 3 && companion.remaining["wild-shape"] === 2, "companion uses selected slot only");
  assert(!updatePlayState(first, { type: "companion", resource: "wild-shape" }, c).companion, "beast cannot cast find familiar");
  const companionShape = updatePlayState(play, { type: "companion", resource: "wild-shape" }, c);
  assert(companionShape.remaining["wild-shape"] === 1 && companionShape.temporaryHp === 0, "companion shape use must not grant temporary HP");
  const long = updatePlayState({ ...first, companion: true, incapacitated: true }, { type: "rest", kind: "long" }, c);
  assert(long.hp === 27 && long.temporaryHp === 0 && long.remaining["wild-shape"] === 2 && !long.formId && !long.companion && long.incapacitated === true, "long rest restores resources without curing unspecified incapacitation");
  const restored = parseDraft(JSON.stringify({ step: "character", build, play: first })).state!;
  assert(restored.play?.formId === "badger" && restored.play.hp === 12 && restored.play.temporaryHp === 9, "form and expenditure survive serialization");
  assert(!normalizePlayState({ ...first, formId: "panther" }, c).formId && !normalizePlayState({ ...first, hp: 0 }, c).formId, "stored form must satisfy both selection and HP guard");
  let state: BuilderState = { step: "character", build, play: first };
  state = switchClass(switchClass(state, "fighter"), "druid");
  assert(state.play?.formId === "badger" && state.build.identity.name === "苔拉·月痕", "class switching preserves druid resources");
  const archived = parseDraft(JSON.stringify(switchClass(state, "wizard"))).state!;
  assert(archived.profiles?.druid?.play?.formId === "badger", "inactive druid draft restored");
  for (const patch of [{ prepared: ["moonbeam", ...build.choices.druid!.prepared.slice(1)] }, { cantrips: ["fire-bolt", "guidance", "druidcraft"] }, { knownForms: ["cat", "cat", "badger", "wolf"] }, { knownForms: ["cat", "badger", "wolf", "eagle"] }, { order: "unknown" }]) {
    const invalid = structuredClone(build); Object.assign(invalid.choices.druid!, patch);
    assert(!validateBuild(invalid).canGenerate, `invalid druid choice rejected: ${JSON.stringify(patch)}`);
  }
  const warden = structuredClone(build); warden.choices.druid!.order = "warden"; warden.choices.druid!.cantrips = ["guidance", "thorn-whip"];
  assert(validateBuild(warden).canGenerate && deriveCharacter(warden).skills.nature.modifier === 3 && deriveCharacter(warden).armorClass === 15, "warden removes magician bonus without granting unowned armor");
  const wizard = defaultBuild("wizard"); wizard.identity = build.identity; wizard.choices.wizard!.earlyBook[0] = "healing-word";
  assert(!validateBuild(wizard).canGenerate, "shared spell dictionary cannot admit druid spells into wizard book");
  const corrupted = structuredClone(build) as unknown as { choices: { druid: unknown } }; corrupted.choices.druid = null;
  assert(!parseDraft(JSON.stringify({ build: corrupted })).state, "malformed druid data safely rejected");
}
