import { defaultBuild } from "../src/rules/defaultBuild";
import { deriveCharacter } from "../src/rules/engine/deriveCharacter";
import { normalizePlayState, updatePlayState } from "../src/rules/engine/playState";
import { derivePrimalCompanion } from "../src/rules/engine/primalCompanion";
import { validateBuild } from "../src/rules/validator/validateBuild";
import { parseDraft, switchClass, type BuilderState } from "../src/store/draft";
import { RANGER_PREPARABLE, PRIMAL_FORMS } from "../src/data/ranger";

// 检查独立伙伴状态与资源原子操作，覆盖读档、死亡和休息后的边界。
export function rangerChecks(assert: (ok: boolean, message: string) => void) {
  const b = defaultBuild("ranger"); b.identity = { name: "林径守望", alignment: "NG" }; const c = deriveCharacter(b);
  assert(validateBuild(b).canGenerate, "default beast master legal");
  assert(c.maxHp === 28 && c.armorClass === 15 && c.hitDie === 10, "ranger dwarf HP and studded leather");
  assert(c.abilities.dexterity.score === 17 && c.abilities.wisdom.score === 15 && c.spellcasting?.dc === 12, "ranger DEX and WIS derived");
  assert(c.savingThrows.strength.modifier === 2 && c.savingThrows.dexterity.modifier === 5, "STR DEX save proficiency");
  assert(c.skills.perception.modifier === 6 && c.passivePerception === 16, "deft explorer expertise");
  assert(c.languages.length === 5 && new Set(c.languages).size === 5, "five total languages");
  assert(c.equipment.find((e) => e.id === "gp")?.quantity === 23 && !c.equipment.some((e) => e.id === "shield"), "combined gear and no starting shield");
  assert(c.attacks.find((a) => a.weaponId === "longbow")?.attackBonus === 7 && c.attacks.find((a) => a.weaponId === "dagger")?.attackBonus === 5, "archery applies only ranged weapons not thrown melee");
  assert(c.attacks.filter((a) => a.mastery?.unlocked).length === 2, "two ranger masteries");
  assert(c.spellcasting!.prepared.length === 5 && c.spellcasting!.cantrips.length === 0, "four selected plus hunters mark without cantrips");
  assert(!c.resources.some((r) => ["spell-slot-2", "pact-slot", "wild-shape", "arcane-recovery"].includes(r.id)), "no other class resources");
  const land = derivePrimalCompanion(c, b.choices.ranger!.primal);
  assert(land.hp === 20 && land.armorClass === 15 && land.attack === 4 && land.damage === "1d8+4", "land scales from WIS not player DEX or archery");
  assert(land.rolls.strength === 4 && land.rolls.intelligence === 1 && land.passivePerception === 14, "primal bond all checks saves and passive perception");
  const sea = derivePrimalCompanion(c, { form: "sea", damage: "piercing", appearance: "海豹" });
  assert(sea.hp === 20 && sea.damage === "1d6+4" && sea.dc === 12 && sea.darkvision === 90, "sea companion stats");
  const sky = derivePrimalCompanion(c, { form: "sky", damage: "slashing", appearance: "鹰" });
  assert(sky.hp === 16 && sky.hitDie === 6 && sky.damage === "1d4+5" && sky.rolls.dexterity === 5 && sky.rolls.strength === 0, "sky independent stats");
  const defensive = structuredClone(b); defensive.choices.ranger!.style = "defense";
  const dc = deriveCharacter(defensive);
  assert(dc.armorClass === 16 && dc.attacks.find((a) => a.weaponId === "longbow")!.attackBonus === 5, "defense replaces archery rather than stacks");
  const lowDex = structuredClone(b); lowDex.abilities.baseAssignment.dexterity = 8; lowDex.abilities.baseAssignment.charisma = 15;
  assert(!!deriveCharacter(lowDex).attacks.find((a) => a.weaponId === "longbow")!.disadvantage && !c.attacks.find((a) => a.weaponId === "longbow")!.disadvantage, "heavy ranged threshold checks DEX");
  const bad = (change: (value: typeof b) => void) => { const value = structuredClone(b); change(value); return !validateBuild(value).canGenerate; };
  assert(bad((v) => { v.choices.ranger!.skills[0] = "arcana"; }), "ranger skill whitelist");
  assert(bad((v) => { v.choices.ranger!.expertise = "arcana"; }), "expertise requires proficiency");
  assert(bad((v) => { v.choices.ranger!.extraLanguages[0] = "dwarvish"; }), "extra language cannot duplicate base language");
  assert(bad((v) => { v.choices.weaponMasteries = ["longbow","longbow"]; }), "distinct masteries required");
  assert(bad((v) => { v.choices.ranger!.prepared[0] = "hunters-mark"; }), "mark does not consume selected preparation");
  assert(bad((v) => { v.choices.ranger!.prepared[0] = "misty-step"; }), "ranger cannot prepare second-level spell at three");
  assert(bad((v) => { v.choices.ranger!.primal = { form: "sky", damage: "piercing", appearance: "鹰" }; }), "sky damage restricted to slashing");
  assert(bad((v) => { v.choices.ranger!.primal.appearance = ""; }), "partner appearance required");
  assert(RANGER_PREPARABLE.length === 8 && PRIMAL_FORMS.length === 3, "curated selection scope");
  let p = normalizePlayState(undefined, c);
  assert(p.primal?.hp === 20 && p.primal.hitDice === 3 && !p.primal.canReplace && p.remaining["spell-slot-1"] === 3, "initial companion and slots");
  const noReplace = updatePlayState(p, { type: "primal-replace", choice: { form: "sky", damage: "slashing", appearance: "鹰" } }, c);
  assert(noReplace.primal!.choice.form === "land", "no replacement before long rest");
  p = updatePlayState(p, { type: "ranger-cast", spellId: "hunters-mark", free: true }, c);
  assert(p.remaining["favored-enemy"] === 1 && p.remaining["spell-slot-1"] === 3 && p.rangerConcentration === "hunters-mark", "free mark spends only favored enemy");
  const wrongFree = updatePlayState(p, { type: "ranger-cast", spellId: "cure-wounds", free: true }, c);
  assert(wrongFree.remaining["spell-slot-1"] === 3, "free source cannot cast other spells");
  p = updatePlayState(p, { type: "ranger-cast", spellId: "ensnaring-strike" }, c);
  assert(p.rangerConcentration === "ensnaring-strike" && p.remaining["spell-slot-1"] === 2, "new concentration replaces old");
  const incapable = updatePlayState(p, { type: "incapacitated", value: true }, c);
  assert(!incapable.rangerConcentration && updatePlayState(incapable, { type: "ranger-cast", spellId: "hunters-mark" }, c).remaining["spell-slot-1"] === 2, "incapacitated ends concentration and blocks casting");
  p = updatePlayState(p, { type: "primal-temp", value: 5 }, c);
  const hurt = updatePlayState(p, { type: "primal-damage", amount: 8 }, c);
  assert(hurt.primal!.hp === 17 && hurt.primal!.temporaryHp === 0 && hurt.hp === 28 && p.primal!.hp === 20, "partner damage independent and immutable");
  const zero = updatePlayState(hurt, { type: "primal-damage", amount: 50 }, c);
  assert(zero.primal!.hp === 0 && zero.primal!.status === "alive", "zero HP not automatic death");
  assert(updatePlayState(zero, { type: "primal-revive", withinHour: true }, c).remaining["spell-slot-1"] === 2, "revive requires actual dead status");
  const dead = updatePlayState(zero, { type: "primal-dead" }, c);
  assert(dead.primal!.status === "dead" && updatePlayState(dead, { type: "primal-hp", value: 20 }, c).primal!.hp === 0, "dead cannot be healed by HP tracker");
  assert(updatePlayState(dead, { type: "primal-revive", withinHour: false }, c).remaining["spell-slot-1"] === 2, "revival requires one-hour confirmation");
  const spent = updatePlayState(dead, { type: "resource", id: "spell-slot-1", value: 0 }, c);
  assert(updatePlayState(spent, { type: "primal-revive", withinHour: true }, c).primal!.status === "dead", "free mark cannot pay revival cost");
  const pending = updatePlayState(dead, { type: "primal-revive", withinHour: true }, c);
  assert(pending.primal!.status === "reviving" && pending.primal!.hp === 0 && pending.remaining["spell-slot-1"] === 1, "revival costs slot before one minute completes");
  assert(updatePlayState(pending, { type: "primal-revive", withinHour: true }, c).remaining["spell-slot-1"] === 1, "repeated revival cannot double charge");
  const revived = updatePlayState(pending, { type: "primal-revive-complete" }, c);
  assert(revived.primal!.status === "alive" && revived.primal!.hp === 20 && revived.hp === 28, "revival completion restores only companion");
  const short = updatePlayState(hurt, { type: "rest", kind: "short" }, c);
  assert(short.primal!.hp === 17 && short.remaining["spell-slot-1"] === 2 && short.remaining["favored-enemy"] === 1 && !short.rangerConcentration, "short rest neither heals partner nor restores spell resources");
  const long = updatePlayState(hurt, { type: "rest", kind: "long" }, c);
  assert(long.primal!.hp === 20 && long.primal!.canReplace && long.remaining["spell-slot-1"] === 3 && long.remaining["favored-enemy"] === 2, "long rest allows replacement and restores living partner");
  assert(updatePlayState(dead, { type: "rest", kind: "long" }, c).primal!.status === "dead", "long rest does not resurrect old companion");
  const flight = updatePlayState(long, { type: "primal-replace", choice: { form: "sky", damage: "slashing", appearance: "鹰" } }, c);
  assert(flight.primal!.hp === 16 && flight.primal!.choice.form === "sky" && !flight.primal!.canReplace, "replacement uses new stat block and consumes rest opportunity");
  assert(updatePlayState(flight, { type: "primal-replace", choice: { form: "land", damage: "piercing", appearance: "狼" } }, c).primal!.choice.form === "sky", "no repeat replacement for free healing");
  const afterAdventure = updatePlayState(long, { type: "primal-damage", amount: 1 }, c);
  assert(!afterAdventure.primal!.canReplace, "replacement opportunity expires when adventuring resumes");
  const rangerDead = updatePlayState(flight, { type: "ranger-dead" }, c);
  assert(rangerDead.hp === 0 && rangerDead.primal!.status === "absent" && !rangerDead.rangerConcentration, "ranger death dismisses companion");
  assert(updatePlayState(rangerDead, { type: "rest", kind: "long" }, c).remaining["spell-slot-1"] === rangerDead.remaining["spell-slot-1"] && !updatePlayState(rangerDead, { type: "rest", kind: "long" }, c).primal!.canReplace, "zero HP cannot claim long rest");
  const restored = parseDraft(JSON.stringify({ build:b, step:"character", play:pending })).state!;
  assert(restored.play?.primal?.status === "reviving" && restored.play.remaining["spell-slot-1"] === 1, "revival pending persists without refund");
  const normalized = normalizePlayState({ primal: { choice:{form:"__proto__",damage:"unknown",appearance:123},hp:999,hitDice:10,status:"invalid" }, rangerConcentration:"meteor-swarm" },c);
  assert(normalized.primal!.hp === 20 && normalized.primal!.hitDice === 3 && !normalized.rangerConcentration, "tampered companion state bounded");
  const changedBuild = structuredClone(b); changedBuild.choices.ranger!.primal = { form:"sky",damage:"slashing",appearance:"鹰" };
  assert(normalizePlayState(hurt,deriveCharacter(changedBuild)).primal!.choice.form === "land", "editing initial choice does not replace current companion");
  let state:BuilderState = { step:"character",build:b,play:pending };
  for(const id of ["fighter","wizard","druid","warlock","ranger"] as const) state=switchClass(state,id);
  assert(state.play?.primal?.status === "reviving" && state.play.remaining["spell-slot-1"] === 1, "five-profile switching preserves independent partner state");
  assert(parseDraft(JSON.stringify(state)).state?.profiles?.warlock?.build.classId === "warlock", "all inactive profiles survive restoration");
  assert(normalizePlayState(p,deriveCharacter(defaultBuild("fighter"))).primal === undefined, "partner fields cannot leak into fighter");
  const missing = structuredClone(b); (missing.choices.ranger as unknown as Record<string,unknown>).primal = null;
  assert(!parseDraft(JSON.stringify({build:missing,step:"character"})).state, "malformed partner build rejected at shape boundary");
}
