import { defaultBuild } from "../src/rules/defaultBuild";
import { deriveCharacter } from "../src/rules/engine/deriveCharacter";
import { deriveWarlockPlay, warlockCantrip } from "../src/rules/engine/warlock";
import { normalizePlayState, updatePlayState } from "../src/rules/engine/playState";
import { validateBuild } from "../src/rules/validator/validateBuild";
import { parseDraft, switchClass, type BuilderState } from "../src/store/draft";
import { FIEND_SPELLS, eligibleTarget } from "../src/data/warlock";

// 针对职业差异验证：契约位恢复、祈唤绑定、临时 HP 与普通施法职业隔离。
export function warlockChecks(assert: (ok: boolean, message: string) => void) {
  const build = defaultBuild("warlock"); build.identity = { name: "凯恩·烬契", alignment: "N" };
  const c = deriveCharacter(build);
  assert(validateBuild(build).canGenerate, "default fiend warlock legal");
  assert(c.maxHp === 27 && c.armorClass === 13 && c.hitDie === 8, "warlock dwarf HP and leather AC");
  assert(c.abilities.charisma.score === 17 && c.spellcasting?.attack === 5 && c.spellcasting.dc === 13, "warlock uses CHA");
  assert(c.savingThrows.charisma.modifier === 5 && c.savingThrows.wisdom.modifier === 3, "warlock CHA/WIS saves");
  assert(c.skills.insight.proficiency === "proficient" && c.skills.stealth.proficiency === "proficient", "wayfarer skills");
  assert(c.equipment.find((e) => e.id === "dagger")?.quantity === 4 && c.equipment.find((e) => e.id === "gp")?.quantity === 31, "combined warlock equipment");
  assert(c.spellcasting!.prepared.length === 8 && FIEND_SPELLS.every((id) => c.spellcasting!.prepared.includes(id)), "fiend 2024 automatic spells");
  assert(!c.resources.some((r) => ["spell-slot-1", "arcane-recovery", "wild-shape"].includes(r.id)), "other class resources isolated");
  assert(c.pactMagic?.slotLevel === 2 && c.pactMagic.darkBlessing === 6 && c.pactMagic.concentrationAdvantage, "pact and invocation derived effects");
  assert(c.savingThrows.constitution.state === "normal", "eldritch mind does not grant all CON saves advantage");
  const blast = warlockCantrip(c, "eldritch-blast")!;
  assert(blast.damage === "1d10+3 力场" && blast.range === 120 && blast.push, "single beam and targeted invocations");
  assert(!warlockCantrip(c, "constructor") && !eligibleTarget("repelling-blast", "mind-sliver", ["mind-sliver"]), "safe lookup and attack-only repelling");
  const alternative = structuredClone(build);
  alternative.choices.warlock!.cantrips = ["eldritch-blast", "mind-sliver"];
  alternative.choices.warlock!.invocations = [{ id: "agonizing-blast", target: "eldritch-blast" }, { id: "agonizing-blast", target: "mind-sliver" }, { id: "eldritch-spear", target: "mind-sliver" }];
  assert(validateBuild(alternative).canGenerate, "repeatable invocation accepts distinct targets");
  const alt = deriveCharacter(alternative);
  assert(warlockCantrip(alt, "mind-sliver")?.damage === "1d6+3 心灵" && warlockCantrip(alt, "mind-sliver")?.range === 150 && !warlockCantrip(alt, "eldritch-blast")?.push, "range and damage limited to bound cantrip");
  const bad = (mutate: (b: typeof build) => void) => { const b = structuredClone(build); mutate(b); return !validateBuild(b).canGenerate; };
  assert(bad((b) => { b.choices.warlock!.invocations[1] = b.choices.warlock!.invocations[0]; }), "duplicate invocation target rejected");
  assert(bad((b) => { b.choices.warlock!.invocations[1] = { id: "eldritch-mind" }; }), "nonrepeatable duplicate rejected");
  assert(bad((b) => { b.choices.warlock!.invocations[0].target = "prestidigitation"; }), "nondamaging target rejected");
  assert(bad((b) => { b.choices.warlock!.cantrips[0] = "mind-sliver"; }), "changing cantrip invalidates old bindings");
  assert(bad((b) => { b.choices.warlock!.invocations[0] = { id: "lifedrinker" }; }), "unavailable invocation rejected");
  assert(bad((b) => { b.choices.warlock!.prepared = ["hex", "misty-step", "invisibility", "darkness"]; }), "level-three progression allows at most two second-level spells");
  assert(bad((b) => { b.choices.warlock!.prepared[0] = "command"; }), "automatic spell cannot occupy selected preparation");
  assert(bad((b) => { b.choices.warlock!.prepared[0] = "cure-wounds"; }), "class spell whitelist");
  let p = normalizePlayState(undefined, c);
  assert(p.remaining["pact-slot"] === 2 && p.remaining.lucky === 2 && p.warlockArmor === "leather", "default play resources");
  assert(updatePlayState(p, { type: "magical-cunning" }, c).remaining["magical-cunning"] === 1, "full slots cannot waste cunning");
  p = updatePlayState(p, { type: "cast-pact", spellId: "armor-of-agathys" }, c);
  assert(p.remaining["pact-slot"] === 1 && p.temporaryHp === 10 && p.agathys === true, "second-level agathys applied atomically");
  const blessing = updatePlayState(p, { type: "dark-blessing" }, c);
  assert(blessing.temporaryHp === 10 && blessing.agathys === true, "blessing neither stacks nor ends agathys");
  const damage = updatePlayState(p, { type: "damage", amount: 12 }, c);
  assert(damage.hp === 25 && damage.temporaryHp === 0 && !damage.agathys, "damage spends temp first and ends agathys when depleted");
  p = updatePlayState(p, { type: "cast-pact", spellId: "hex" }, c);
  assert(p.remaining["pact-slot"] === 0 && updatePlayState(p, { type: "cast-pact", spellId: "hex" }, c).remaining["pact-slot"] === 0, "pact slot cannot underflow");
  p = updatePlayState(p, { type: "magical-cunning" }, c);
  assert(p.remaining["pact-slot"] === 1 && p.remaining["magical-cunning"] === 0, "cunning restores one with one use");
  assert(updatePlayState(p, { type: "magical-cunning" }, c).remaining["pact-slot"] === 1, "cunning cannot repeat before long rest");
  assert(updatePlayState(p, { type: "cast-pact", spellId: "false-life" }, c).remaining["pact-slot"] === 1, "unprepared spell cannot spend pact slot");
  assert(updatePlayState({ ...p, incapacitated: true }, { type: "cast-pact", spellId: "hex" }, c).remaining["pact-slot"] === 1, "incapacitated cannot cast");
  p = updatePlayState(p, { type: "resource", id: "lucky", value: 0 }, c);
  const short = updatePlayState(p, { type: "rest", kind: "short" }, c);
  assert(short.remaining["pact-slot"] === 2 && short.remaining["magical-cunning"] === 0 && short.remaining.lucky === 0 && !short.agathys, "short rest restores only pact slots and expires one-hour spell");
  const long = updatePlayState(p, { type: "rest", kind: "long" }, c);
  assert(long.remaining["pact-slot"] === 2 && long.remaining["magical-cunning"] === 1 && long.remaining.lucky === 2 && long.temporaryHp === 0, "long rest restores daily warlock resources");
  assert(updatePlayState(p, { type: "fiendish-vigor" }, c).temporaryHp === p.temporaryHp, "unselected vigor cannot grant HP");
  const defensive = structuredClone(build);
  defensive.choices.warlock!.invocations = [{ id: "armor-of-shadows" }, { id: "fiendish-vigor" }, { id: "devils-sight" }];
  const defense = deriveCharacter(defensive);
  assert(validateBuild(defensive).canGenerate && defense.pactMagic!.atWill.length === 2 && defense.pactMagic!.devilsSight, "defensive invocation route legal");
  let armor = updatePlayState(normalizePlayState(undefined, defense), { type: "warlock-armor", value: "mage-armor" }, defense);
  assert(deriveWarlockPlay(defense, armor).armorClass === 15 && armor.remaining["pact-slot"] === 2, "mage armor replaces leather without pact cost");
  armor = updatePlayState(armor, { type: "fiendish-vigor" }, defense);
  assert(armor.temporaryHp === 12 && updatePlayState(armor, { type: "fiendish-vigor" }, defense).temporaryHp === 12, "vigor maximum 12 nonstacking");
  assert(deriveWarlockPlay(c, normalizePlayState(armor, c)).armorClass === 12, "removing armor invocation leaves unarmored rather than reequipping leather");
  assert(deriveWarlockPlay(defense, updatePlayState(armor, { type: "rest", kind: "long" }, defense)).armorClass === 12, "eight-hour rest expires mage armor");
  const saved = parseDraft(JSON.stringify({ step: "character", build: defensive, play: armor })).state!;
  assert(saved.play?.warlockArmor === "mage-armor" && saved.play.temporaryHp === 12, "armor and resources persist");
  let state: BuilderState = { step: "character", build, play: p };
  for (const id of ["fighter", "wizard", "druid", "warlock"] as const) state = switchClass(state, id);
  assert(state.play?.remaining["magical-cunning"] === 0 && state.build.identity.name === build.identity.name, "four-profile switching preserves resources");
  assert(parseDraft(JSON.stringify({ ...state, step: "character" })).state?.profiles?.druid?.build.classId === "druid", "four profiles restore together");
  const broken = structuredClone(build); broken.choices.warlock!.invocations = [];
  assert(parseDraft(JSON.stringify({ build: broken, step: "character" })).state?.step === "review", "incomplete invocations cannot bypass generation gate");
  assert(!parseDraft(JSON.stringify({ build: { ...build, choices: { warlock: { invocations: null } } } })).state, "malformed warlock draft safely rejected");
}
